function VisCon_AboutDlg()
AboutMsg=sprintf([...
    'VisualConnectome Version 0.20alpha\n\n'...
    'Author: Dai Dai, Email: solar2ain@gmail.com\n\n'...
    'NICA Group, CASIA\n\n'...
    'Copyright 2010-2010, Dai Dai'...
    ]);
msgbox(AboutMsg,'About VisualConnectome','help','modal');
end