%This function sets toolbar property.
function VisCon_Toolbar()
global gFigAxes;
hFig=findobj('Tag','VisConFig');
hTbar=findobj(hFig,'Tag','VisConTbar');
%Delete toolbar if it exists
if ~isempty(hTbar), delete(hTbar);  end
%Create toolbar
hTbar=uitoolbar(hFig,'Tag','VisConTbar');
%Create Open Button
uipushtool('Parent',hTbar,'Tag','UiPushOpen','Separator','off',...
    'TooltipString','Open VisualConnectome File','Enable','on',...
    'Separator','off','BusyAction','cancel','Interruptible','off',...
    'CData',gFigAxes.TbarIcons{1},...
    'ClickedCallback','VisCon_OpenDlg');
%Create Save As Button
uipushtool('Parent',hTbar,'Tag','UiPushSave','Separator','off',...
    'TooltipString','Save As...','Enable','on',...
    'Separator','off','BusyAction','cancel','Interruptible','off',...
    'CData',gFigAxes.TbarIcons{2},...
    'ClickedCallback','VisCon_SaveDlg');
%Create Toggle Surface Visibility Button
uitoggletool('Parent',hTbar,'Tag','UiToggSurf','Separator','on',...
    'TooltipString','Toggle Surface Visibility','Enable','on',...
    'BusyAction','cancel','Interruptible','off',...
    'State','off','CData',gFigAxes.TbarIcons{3},...
    'OffCallback','BrainSurf off','OnCallback','BrainSurf on');
%Create Toggle Axes Indicator Button
uitoggletool('Parent',hTbar,'Tag','UiToggAxesInd','Separator','off',...
    'TooltipString','Toggle Axes Indicator','Enable','on',...
    'BusyAction','cancel','Interruptible','off',...
    'State','on','CData',gFigAxes.TbarIcons{4},...
    'OffCallback','VisCon_AxesInd off','OnCallback','VisCon_AxesInd on');
%Create Toggle Edge Colorbar Button
uitoggletool('Parent',hTbar,'Tag','UiToggEdgeCbar','Separator','off',...
    'TooltipString','Toggle Edge Colorbar','Enable','on',...
    'BusyAction','cancel','Interruptible','off',...
    'State','on','CData',gFigAxes.TbarIcons{5},...
    'OffCallback','VisCon_EdgeCbar off','OnCallback','VisCon_EdgeCbar on');
%Create Toggle Information Box Button
uitoggletool('Parent',hTbar,'Tag','UiToggInformBox','Separator','off',...
    'TooltipString','Toggle Information Box','Enable','on',...
    'BusyAction','cancel','Interruptible','off',...
    'State','on','CData',gFigAxes.TbarIcons{6},...
    'OffCallback','VisCon_InformBox off','OnCallback','VisCon_InformBox on');
%Create Absolute Threshold Button
uipushtool('Parent',hTbar,'Tag','UiPushAbsThres','Separator','on',...
    'TooltipString','Absolute Threshold','Enable','on',...
    'BusyAction','cancel','Interruptible','off',...
    'CData',gFigAxes.TbarIcons{7},...
    'ClickedCallback','VisCon_AbsThresDlg');
%Create Proportional Threshold Button
uipushtool('Parent',hTbar,'Tag','UiPushPropThres','Separator','off',...
    'TooltipString','Proportional Threshold','Enable','on',...
    'BusyAction','cancel','Interruptible','off',...
    'CData',gFigAxes.TbarIcons{8},...
    'ClickedCallback','VisCon_PropThresDlg');
end