function VisCon_AboutDlg()
AboutMsg = [{'\bf\fontsize{10}VisualConnectome Version 0.35a'},...
    {''},...
    {'\fontsize{9}               Author: Dai Dai'},...
    {'            NICA Group, CASIA'}...
    {'       Email: solar2ain@gmail.com'},...
    {'     Copyright 2010-2011, Dai Dai'}];
CreateMode.WindowStyle = 'modal';
CreateMode.Interpreter = 'tex';
msgbox(AboutMsg,'About VisualConnectome','help',CreateMode);
end